# conf/app.yaml

# FastAPI server (api/main.py should read these)
api:
  host: "0.0.0.0"
  port: 8000
  url: "http://127.0.0.1:8000/infer"  # used by patient_cli; set to null to call local function directly

# Generation defaults
gen_max_new_tokens: 384

# Where artifacts live
paths:
  models:
    textlm: "out/models/textlm"
    sft: "out/models/sft"
  tokenizer: "out/tokenizer"
  index:
    faiss: "data/index/faiss"

# Personas control style & safety behavior
default_persona: "patient"
personas:
  patient:
    style: "friendly, simple, step-by-step; short paragraphs"
    enforce_otc: true
    include_disclaimer: true
  researcher:
    style: "concise, technical, bullet-pointed with citations"
    enforce_otc: false
    include_disclaimer: false
  default:
    style: "neutral"
    enforce_otc: true
    include_disclaimer: true

rag:
  index_dir: "data/index/faiss"
  corpus_file: "data/corpus/corpus.jsonl.gz"

  # chunking params
  chunk_size: 512
  chunk_overlap: 50
